// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


var firstName = "jim";

console.log(firstName);

var jim = {
  name: {
    firstName: "jim",
    lastName: "craft"
  },
  id: 0
};

exports.jim = jim;
exports.firstName = firstName;
/*  Not a pure module */
